// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package sqlc

import (
	"context"
)

const getAllGames = `-- name: GetAllGames :many
SELECT name, description, genre
FROM GAMES
`

type GetAllGamesRow struct {
	Name        string
	Description string
	Genre       NullGenre
}

func (q *Queries) GetAllGames(ctx context.Context) ([]GetAllGamesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllGamesRow
	for rows.Next() {
		var i GetAllGamesRow
		if err := rows.Scan(&i.Name, &i.Description, &i.Genre); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
