// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetByEmail(ctx context.Context, email string) (User, error)
	Save(ctx context.Context, arg SaveParams) error
}

var _ Querier = (*Queries)(nil)
