// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getByEmail = `-- name: GetByEmail :one
SELECT id, username, email, password, created_at, updated_at 
FROM users WHERE email = $1
`

func (q *Queries) GetByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const save = `-- name: Save :exec
insert into users (id, username, email, password)
values ($1, $2, $3, $4)
`

type SaveParams struct {
	ID       uuid.UUID
	Username string
	Email    string
	Password string
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.ExecContext(ctx, save,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Password,
	)
	return err
}
